version: '3.9'

services:

  gateway:
    build:
      context: .
      dockerfile: docker/gateway.dockerfile
    environment:
      NODE_ENV: production
      PORT: 80
      GRAPHQL_PATH: ${GRAPHQL_PATH}
      TOKEN_SECRET: ${TOKEN_SECRET}
      TOKEN_ALGORITHM: ${TOKEN_ALGORITHM}
      REDIS_URL: redis://:@redis:6379/0 # database 0 is also used by authentications and users
      SERVICES_AUTHENTICATIONS_URL: http://authentications:80/graphql
      SERVICES_USERS_URL: http://users:80/graphql
      SERVICES_PRODUCTS_URL: http://products:80/graphql
      SERVICES_INVENTORIES_URL: http://inventories:80/graphql
      SERVICES_PURCHASES_URL: http://purchases:80/graphql
      SERVICES_REVIEWS_URL: http://reviews:80/graphql
    depends_on:
      - authentications
      - users
      - products
      - inventories
      - purchases
      - reviews

  authentications:
    build:
      context: .
      dockerfile: docker/authentications.dockerfile
    environment:
      NODE_ENV: production
      PORT: 80
      GRAPHQL_PATH: ${GRAPHQL_PATH}
      TOKEN_SECRET: ${TOKEN_SECRET}
      TOKEN_ALGORITHM: ${TOKEN_ALGORITHM}
      TOKEN_EXPIRATION_TIME: ${TOKEN_EXPIRATION_TIME}
      DATABASE_URL: postgres://user:password@db:5432/graphmarket
      DATABASE_SSL: 'false'
      DATABASE_SYNCHRONIZE: 'false'
      DATABASE_DROP_SCHEMA: 'false'
      DATABASE_LOGGING: ${DATABASE_LOGGING}
      REDIS_URL: redis://:@redis:6379/0 # database 0 is also used by gateway and users
      ADAPTER_PHONE_USERNAME: ${ADAPTER_PHONE_USERNAME}
      ADAPTER_PHONE_PASSWORD: ${ADAPTER_PHONE_PASSWORD}
      ADAPTER_PHONE_SERVICE_VERIFICATION: ${ADAPTER_PHONE_SERVICE_VERIFICATION}
      ADAPTER_EMAIL_API_KEY: ${ADAPTER_EMAIL_API_KEY}
    depends_on:
      - db
      - redis

  users:
    build:
      context: .
      dockerfile: docker/users.dockerfile
    environment:
      NODE_ENV: production
      PORT: 80
      GRAPHQL_PATH: ${GRAPHQL_PATH}
      TOKEN_SECRET: ${TOKEN_SECRET}
      TOKEN_ALGORITHM: ${TOKEN_ALGORITHM}
      DATABASE_URL: postgres://user:password@db:5432/graphmarket
      DATABASE_SSL: 'false'
      DATABASE_SYNCHRONIZE: 'false'
      DATABASE_DROP_SCHEMA: 'false'
      DATABASE_LOGGING: ${DATABASE_LOGGING}
      REDIS_URL: redis://:@redis:6379/0 # database 0 is also used by gateway and authentications
      ADAPTER_PHONE_USERNAME: ${ADAPTER_PHONE_USERNAME}
      ADAPTER_PHONE_PASSWORD: ${ADAPTER_PHONE_PASSWORD}
      ADAPTER_PHONE_SERVICE_VERIFICATION: ${ADAPTER_PHONE_SERVICE_VERIFICATION}
      ADAPTER_EMAIL_API_KEY: ${ADAPTER_EMAIL_API_KEY}
      ADAPTER_UPLOAD_CLOUD_NAME: ${ADAPTER_UPLOAD_CLOUD_NAME}
      ADAPTER_UPLOAD_API_KEY: ${ADAPTER_UPLOAD_API_KEY}
      ADAPTER_UPLOAD_API_SECRET: ${ADAPTER_UPLOAD_API_SECRET}
      ADAPTER_UPLOAD_FOLDER: ${ADAPTER_UPLOAD_FOLDER}
      ADAPTER_UPLOAD_MAX_FILE_SIZE: ${ADAPTER_UPLOAD_MAX_FILE_SIZE}
      ADAPTER_UPLOAD_MAX_FILES: ${ADAPTER_UPLOAD_MAX_FILES}
    depends_on:
      - db
      - redis

  products:
    build:
      context: .
      dockerfile: docker/products.dockerfile
    environment:
      NODE_ENV: production
      PORT: 80
      GRAPHQL_PATH: ${GRAPHQL_PATH}
      DATABASE_URL: postgres://user:password@db:5432/graphmarket
      DATABASE_SSL: 'false'
      DATABASE_SYNCHRONIZE: 'false'
      DATABASE_DROP_SCHEMA: 'false'
      DATABASE_LOGGING: ${DATABASE_LOGGING}
      REDIS_URL: redis://:@redis:6379/1
      ADAPTER_UPLOAD_CLOUD_NAME: ${ADAPTER_UPLOAD_CLOUD_NAME}
      ADAPTER_UPLOAD_API_KEY: ${ADAPTER_UPLOAD_API_KEY}
      ADAPTER_UPLOAD_API_SECRET: ${ADAPTER_UPLOAD_API_SECRET}
      ADAPTER_UPLOAD_FOLDER: ${ADAPTER_UPLOAD_FOLDER}
      ADAPTER_UPLOAD_MAX_FILE_SIZE: ${ADAPTER_UPLOAD_MAX_FILE_SIZE}
      ADAPTER_UPLOAD_MAX_FILES: ${ADAPTER_UPLOAD_MAX_FILES}
    depends_on:
      - db
      - redis

  inventories:
    build:
      context: .
      dockerfile: docker/inventories.dockerfile
    environment:
      NODE_ENV: production
      PORT: 80
      GRAPHQL_PATH: ${GRAPHQL_PATH}
      DATABASE_URL: postgres://user:password@db:5432/graphmarket
      DATABASE_SSL: 'false'
      DATABASE_SYNCHRONIZE: 'false'
      DATABASE_DROP_SCHEMA: 'false'
      DATABASE_LOGGING: ${DATABASE_LOGGING}
      REDIS_URL: redis://:@redis:6379/2
    depends_on:
      - db
      - redis

  purchases:
    build:
      context: .
      dockerfile: docker/purchases.dockerfile
    environment:
      NODE_ENV: production
      PORT: 80
      GRAPHQL_PATH: ${GRAPHQL_PATH}
      DATABASE_URL: postgres://user:password@db:5432/graphmarket
      DATABASE_SSL: 'false'
      DATABASE_SYNCHRONIZE: 'false'
      DATABASE_DROP_SCHEMA: 'false'
      DATABASE_LOGGING: ${DATABASE_LOGGING}
      REDIS_URL: redis://:@redis:6379/3
      ADAPTER_EMAIL_API_KEY: ${ADAPTER_EMAIL_API_KEY}
    depends_on:
      - db
      - redis

  reviews:
    build:
      context: .
      dockerfile: docker/reviews.dockerfile
    environment:
      NODE_ENV: production
      PORT: 80
      GRAPHQL_PATH: ${GRAPHQL_PATH}
      DATABASE_URL: postgres://user:password@db:5432/graphmarket
      DATABASE_SSL: 'false'
      DATABASE_SYNCHRONIZE: 'false'
      DATABASE_DROP_SCHEMA: 'false'
      DATABASE_LOGGING: ${DATABASE_LOGGING}
      REDIS_URL: redis://:@redis:6379/4
    depends_on:
      - db
      - redis

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: graphmarket

  redis:
    image: redis
    depends_on:
      - db
