version: '3.8'

services:
  web:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - database
      - redis
    links:
      - database
      - redis
    environment:
      - NODE_ENV=development
      - PORT=8080
      - DATABASE_URL=postgres://postgres:password@database:5432/graphql_db
      - REDIS_URL=redis://redis:6379/0
      - JWT_SECRET=secret

  database:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=graphql_db

  redis:
    image: redis:3.2.8
    ports:
      - '6379:6379'
