version: '3.7'

services:
  web-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: graphql-template
    volumes:
      - ./src:/home/node/app/src
    expose:
      - '8080'
    ports:
      - '8080:8080'
    command: npm run start:prod
