name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Test on node ${{ matrix.node }}

    runs-on: ubuntu-latest

    container: node:${{ matrix.node }}-jessie

    strategy:
      matrix:
        node: [10, 12, 14]

     services:
      postgres:
        image: database
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_DB: graphmarket-test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout main
        uses: actions/checkout@v2
      - name: Use node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npm ci
      - name: Linting
        run: npm run lint
      - name: Building
        run: npm run build
      - name: Testing
        run: npm test
        env:
          DATABASE_URL: postgres://postgres:password@localhost:5432/graphmarket-test
      - name: Generate coverage
        run: npm run coverage
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
