name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Test on node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [10, 12, 14]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout main
        uses: actions/checkout@v2
      - name: Use node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npm ci
      - name: Linting
        run: npm run lint
      - name: Prettify
        run: npm run prettify
      - name: Building
        run: npm run build
      - name: Testing
        run: npm test
